Fix repeat; rewrite multi-head attention layer
FluxML/Metalhead.jl pull request #158
Opened 2022-05-25 03:55 UTC by theabhirath

Closes #157. Also borrows from the excellent implementation of `MHAttention` at https://github.com/avik-pal/Lux.jl/pull/29 to remove the NeuralAttentionlib dep, hopefully reducing time for `using Metalhead`

2022-05-25 14:29 UTC, darsnack requested changes

2022-05-27 13:33 UTC, darsnack commented
It's a bit confusing...fields of structs should be `Int` and functions/constructor arguments should be `Integer`. You want the fields to be a concrete type for performance, you want arguments to be permissive and let the compiler auto-convert when needed.

2022-05-27 13:47 UTC, theabhirath commented
> It's a bit confusing...fields of structs should be `Int` and functions/constructor arguments should be `Integer`. You want the fields to be a concrete type for performance, you want arguments to be permissive and let the compiler auto-convert when needed.

Gotcha, that makes sense

2022-05-27 13:49 UTC, darsnack commented on src/other/mlpmixer.jl
> +                                  mlp_layer(planes, Integer(mlp_ratio * planes); dropout, activation),
```suggestion
                                  mlp_layer(planes, Int(mlp_ratio * planes); dropout, activation),
```

2022-05-27 13:50 UTC, darsnack approved these changes
Sorry for the confusion, that was only meant to be a minor suggestion 😅.

2022-05-27 13:52 UTC, theabhirath commented
That's quite alright, it helped me understand the rationale better! I've messed up the commits on this one a little bit though, so #159 supersedes this one

2022-05-27 13:54 UTC, closed without merging