Miscellaneous fixes for MobileNet
FluxML/Metalhead.jl pull request #179
Opened 2022-06-24 02:19 UTC by theabhirath

Closes #178. Also removes an extra fully connected layer in MobileNetv1, making it now conform to the configuration described in the paper. And some minor docs and formatting changes I caught have also made it through

2022-06-24 02:20 UTC, theabhirath commented
This is also another step towards #176, as all the MobileNet models now expose `inchannels` and `classes`

2022-06-24 10:12 UTC, darsnack requested changes

2022-06-24 10:17 UTC, theabhirath commented on src/convnets/mobilenet.jl
> +                       Dense(inchannels, nclasses)))
I feel liked we are going to be making a _huge_ breaking release anyways sometime after my GSoC work lands, so this just gets added to the list

2022-06-24 10:18 UTC, theabhirath commented on src/convnets/convmixer.jl
> +  - `inchannels`: The number of channels in the input. The default value is 3.
I'm working on making this happen for all the docstrings in the new PRs (that is, having the default values in there). I need to push a larger documentation change sometime in the next few weeks and that should probably cover everything

2022-06-24 11:30 UTC, darsnack commented
Yes, this is the main reason I brought it up. I want to make a patch release with the recent changes before merging the breaking overhaul.

2022-06-24 12:38 UTC, theabhirath commented
The breaking change has been undone for now. The rest I think should fit into the patch-release without a problem

2022-06-25 09:01 UTC, darsnack requested changes

2022-06-25 09:01 UTC, darsnack commented on src/convnets/mobilenet.jl
> +                nclasses = 1000)
```suggestion
                fcsize = 1024,
                nclasses = 1000)
```

2022-06-25 09:01 UTC, darsnack commented on src/convnets/mobilenet.jl
> +					 fcsize = 1024,
```suggestion
					     fcsize = 1024,
```

2022-06-25 09:06 UTC, darsnack approved these changes

2022-06-25 10:14 UTC, darsnack commented on src/convnets/mobilenet.jl
> +                       Dense(inchannels, nclasses)))
Or (user) code that relies on the structure but doesn't use Functors.jl. I think previously we decided to consider structural changes as breaking. But the more nuanced question here is whether a structural change that fixes an error is considered a bug fix.

I think probably here no one would complain given how recent the model definitions are.

2022-06-25 16:28 UTC, darsnack commented
Can you rebase with the test changes from #171?

2022-06-26 01:34 UTC, theabhirath commented
....wait. How did the CI go from one check passing to _all_ checks passing

2022-06-26 02:15 UTC, ToucheSir commented
Something to do with #171 disabling tests for some of the largest models?

2022-06-26 02:16 UTC, theabhirath commented
Oh, possibly 🤦🏽 I feel like this is just 50-50 at this point as to whether the tests pass or not

2022-06-26 02:38 UTC, ToucheSir commented
Looks like the failure was a timeout instead of an OOM, so hopefully it was an anomaly!

2022-06-26 15:41 UTC, theabhirath commented
Should be ready for merge and release now 😄

2022-06-26 15:52 UTC, merged

2022-06-27 09:44 UTC, maxfreu commented
Thanks!