Docs rehaul for v0.8
FluxML/Metalhead.jl pull request #242
Opened 2023-06-04 16:04 UTC by theabhirath

This is the last PR for v0.8, and introduces just about enough documentation to ensure that users can find their way around the major parts of the repo. A large swathe of the builders remain undocumented, but that will take time and effort and I would rather get v0.8 out first and then worry about that.

cc @darsnack for suggestions in case something important has been missed.

2023-06-05 05:56 UTC, CarloLucibello commented
We should disallow loading densenet pretrained weights and mark the weight as not available in the docs.

2023-06-05 14:10 UTC, darsnack requested changes
Looks pretty good to me!

Other details that I cannot directly comment on:
- The `DenseNet` docstring has the "Arguments" bullet list indented which is being interpreted as a markdown code block
- The `UNet` docstring has the same issue as `DenseNet`
- The `MLPMixer` + `ResMLP` docstring should list the config types as symbols (i.e. `:small`, `:base`, etc.)

2023-06-05 14:10 UTC, darsnack commented on docs/src/howto/resnet.md
> +And we have a custom model, built with minimal effort! The documentation for `Metalhead.resnet` has been written with extensive care and in as much detail as possible to facilitate user ease. However
```suggestion
And we have a custom model, built with minimal effort! The documentation for `Metalhead.resnet` has been written with extensive care and in as much detail as possible to facilitate ease of use. Still, if you find anything difficult to understand, feel free to open an issue and we will be happy to help you out, and to improve the documentation where necessary.
```

2023-06-05 14:10 UTC, darsnack commented on docs/src/api/utilities.md
> +# Model utilities
Rename this in `docs/make.jl` too

2023-06-05 14:56 UTC, darsnack commented
Also need to remove `DenseNet` from the pretrained models list in test.

2023-06-05 15:45 UTC, theabhirath commented
Done, done, done and done! Hopefully tests pass, and then we can finally release this 😁. I have a ready blog post for the Flux website detailing the major improvements as well, so I can land that PR after we tag 😊.

2023-06-06 01:11 UTC, merged

2023-06-06 01:13 UTC, theabhirath commented
Can I go ahead and tag v0.8 now?

2023-06-06 12:00 UTC, darsnack commented
Yeah go for it