Deprecate older VGG API
FluxML/Metalhead.jl pull request #270
Opened 2024-01-04 05:46 UTC by theabhirath

Fix #269. Also adds the pre-trained API to the docstring of VGG. And a small rewrite of the VGG block, which was written pre-`conv_norm`'s current more powerful form.

Right now the `depwarn` isn't printed by default, should we force it to be true? Or is it reasonable to assume that people will spot this and not upgrade if they don't want to/migrate to the newer API if they want to?

2024-01-04 05:48 UTC, theabhirath commented
P.S. there has to be a way to limit the tests run when we open a PR, because running ResNet/MobileNet tests for a VGG PR seems hugely wasteful. Is there a hook to GH Actions that can let us specify which tests to run via a comment or something?

2024-01-04 13:58 UTC, darsnack requested changes

2024-01-04 13:58 UTC, darsnack commented on src/convnets/vgg.jl
> +
I would not document a deprecated method

2024-01-04 13:58 UTC, darsnack commented on src/convnets/vgg.jl
> +end
Can we move deprecations to a `deprecations.jl` file?

2024-01-04 14:02 UTC, darsnack commented
I disagree—passing tests always seem wasteful 😁. IMO tests that don't always run are as bad as no tests at all.

2024-01-04 14:13 UTC, theabhirath commented
> I disagree—passing tests always seem wasteful 😁. IMO tests that don't always run are as bad as no tests at all.

That makes sense 😂 I was thinking more from the GH actions perspective of how many free minutes we get but I think the individual test sets are executing pretty quickly now so it should be okay

2024-01-04 14:31 UTC, darsnack commented
Public repos have unlimited minutes, so that's not an issue. I guess the only thing is that a single org shares runners across all repos, and there are a fixed amount of runners you can use in parallel. But I haven't noticed this to be an issue; it's not like we are waiting significantly longer to merge PRs.

2024-01-04 15:07 UTC, theabhirath commented
> Public repos have unlimited minutes, so that's not an issue.

Oh, for some reason I thought this was limited 😅 That's perfect then, waiting a bit for a PR to merge is not a problem at all.

2024-01-05 01:50 UTC, darsnack approved these changes

2024-01-05 01:52 UTC, merged